name: Publish Docker Image

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/dsci310-project:latest
            ${{ secrets.DOCKER_USERNAME }}/dsci310-project:${{ github.sha }}